version: 2.1
jobs:
  build:
    working_directory: ~/platform #Here is the answer
    docker:
      - image: cimg/base:stable
      #- image: cimg/python:3.7
    steps:
      - checkout:
          path: ~/platform #Here is the answer
      - run:
          name: Install dependencies
          command: |
            apt install python
            apt install python3
            apt install python3.8-venv
            #pip install colab_ssh
            python3 -m pip install --upgrade pip
            pip3 install colab_ssh
      - run:
          name: Install dependencies
          command: |
            ls -l
            python3 -m venv venv
            . venv/bin/activate
            sudo python3 1.py
      - run:
          name: Run migrations
          command: |
            . venv/bin/activate
            python t.py
